# Archivo FUNDING.yml para MintBridgeXFCE v1.0
# Define las plataformas de financiamiento disponibles para el proyecto

github: [Jramone3]

# Puedes agregar más plataformas cuando estén activas:
# patreon: [Jramone3]
# ko_fi: [Jramone3]
# liberapay: [Jramone3]
# custom: ['https://sites.google.com/view/jramone3']
